name: Github Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: workflow
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.opam/4.10.0
        key: ${{ runner.os }}-opam-${{ hashFiles('**/onotion.opam') }}
    - uses: avsm/setup-ocaml@v1.1.0
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        ocaml-version: "4.10.0"
    - run: opam pin add onotion.dev -n .
    - name: External Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: opam depext -yt onotion
    - name: Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: opam install .
    - name: Build
      run: opam exec -- dune build 
    - name: Install
      run: opam exec -- dune install 
    - name: Export Notion 
      run: opam exec -- onotion export
      env:
        notion_cookies: ${{ secrets.NOTION_COOKIES }}
        active_user: ${{ secrets.ACTIVE_USER }}
    - name: Unzip 
      run: unzip ./notion.zip -d ./notion
    - name: Build site 🔨
      run: |
        ls && pwd
        opam exec -- onotion build
    - name: Deploy to GH Pages 🚀
      uses: JamesIves/github-pages-deploy-action@3.5.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: notion
      

